kind: kafka

kafka:
  bootstrap_servers: "localhost:9092"
  topic: "covid-datos"
  group_id: "clever-samples-service"
  security_protocol: "PLAINTEXT"

service:
  has_root: true       # si la jerarquía empieza por entidad raíz obligatoria
  auto_create: true    # si debe crear entidades automáticamente

entities_api:
  host: "entitiesapi"
  port: 8080
  protocol: "http"

samples_api:
  host: "samplesapi"
  port: 8080
  protocol: "http"
