name: Build Container Release
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "v*"

permissions:
  contents: write

env:
  oci_registry: harbor.gradiant.org/si-tecnove-pr-01577/data_api
  platforms: linux/amd64,linux/arm64

jobs:
  build-container:
    runs-on: [SI, standard]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Enable multi-arch support for releases
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v1
      - name: Login to Gradiant harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.gradiant.org
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      # Enable multi-arch support for releases
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.oci_registry }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # Enable multi-arch support for releases
          platforms: ${{ env.platforms }}
